/-
Copyright (c) 2026 Axiomatic_AI. All rights reserved.
Released under Apache 2.0 license as described in the file LICENSE.
Authors: Winston Yin, Frank Koppens
-/
import AxQM.Basic.API.DeutschGate
import AxQM.Basic.API.ControlledControlledUnitary
import AxQM.Basic.API.ControlBranchExt
import AxQM.Basic.API.HadamardRotation
import AxQM.Basic.API.DeutschUniversality

/-!
# Nielsen & Chuang, Exercise 4.44 (universality of the three-qubit Deutsch gate)

*(N&C p. 198.)*

Show the three-qubit gate G is universal whenever alpha is irrational.

* `deutschGate`
* `deutschGate_conj_mem_deutschReachableEvolutions` — the physical gate `deutschGate α`, placed on
  register wires, is a generator of the reachable submonoid `deutschReachableEvolutions`, whose
  data-register actions are dense in `U(2ⁿ)` up to a global phase — so `G` with ancillas is
  universal for `α` irrational.
-/

noncomputable section

namespace AxQM

/-- The **three-qubit Deutsch gate** `G = C²(iR_x(πα))` (Nielsen & Chuang, Exercise 4.44): the
doubly-controlled application of the Deutsch target gate `iRxGate (πα) = iR_x(πα)` to the target
qubit, i.e. `iR_x(πα)` fires on the third qubit exactly when both control qubits are `|1⟩`. Built as
`ccontrolledUnitary (iRxGate (π·α))`, so it is automatically a unitary `Evolution`. -/
def deutschGate (α : ℝ) : Evolution (qubit.compose (qubit.compose qubit)) :=
  ccontrolledUnitary (iRxGate (Real.pi * α))

/-- **The Deutsch gate `G` generates the universal register submonoid.** For a register encoding
`fullEnc : (Fin M → Fin 2) ≃ Fin (8·r)`, a `rest`-encoding `restEnc : (Fin (M - 3) → Fin 2) ≃
Fin r`, a data encoding `dataEnc : (Fin m → Fin 2) ≃ Fin d`, a data-ancilla wire split `e : Fin
M ≃ Fin m ⊕ Fin n`, two distinct ancilla wires `a₀ ≠ a₁` and a data wire `j`, the physical
Deutsch gate `deutschGate α` — transported to `qudit 8` (`threeQuditIso`), tensored with the
identity on the remaining `qudit r`, and conjugated by the register-permutation gate `quditPerm
ρ` — is a member of the reachable `G`-circuit submonoid `deutschReachableEvolutions fullEnc
dataEnc e α` (the submonoid whose data-register actions are dense in `U(2ⁿ)` up to a global
phase).

The reachable submonoid is generated by the wire-placements of `deutschGate α` itself. The
conjugation and tensor factors are the physical relabelling of the three placement wires among
the `M` register wires; they are unavoidable because `deutschGate α` acts on three qubits of a
larger register.
-/
theorem deutschGate_conj_mem_deutschReachableEvolutions {M m n r d : ℕ}
    (fullEnc : (Fin M → Fin 2) ≃ Fin (8 * r)) (restEnc : (Fin (M - 3) → Fin 2) ≃ Fin r)
    (dataEnc : (Fin m → Fin 2) ≃ Fin d) (e : Fin M ≃ Fin m ⊕ Fin n) (α : ℝ)
    (a₀ a₁ : Fin n) (ha : a₀ ≠ a₁) (j : Fin m) :
    ∃ e₃ : Fin M ≃ Fin 3 ⊕ Fin (M - 3),
      quditPerm (fullEnc.symm.trans (Concrete.regTensorEnc e₃ restEnc)).symm
          * Evolution.congr (quditProdIso 8 r).symm
              ((Evolution.congr threeQuditIso (deutschGate α)).tmul Evolution.id)
          * quditPerm (fullEnc.symm.trans (Concrete.regTensorEnc e₃ restEnc))
        ∈ deutschReachableEvolutions fullEnc dataEnc e α := sorry

end AxQM
