/-
Copyright (c) 2026 Axiomatic_AI. All rights reserved.
Released under Apache 2.0 license as described in the file LICENSE.
Authors: Winston Yin, Frank Koppens
-/
module

public import Mathlib.GroupTheory.Subgroup.Centralizer

/-!
# Commutativity of a subgroup generated by a set

## Main results

* `Subgroup.isMulCommutative_closure_iff`: `closure k` is commutative iff every pair of
  elements of `k` commutes.

-/

@[expose] public section

namespace Subgroup

section
variable {G G' : Type*} [Group G] [Group G']
variable {H K : Subgroup G}
variable (H)

/-- The subgroup `closure k` generated by `k` is commutative if and only if every pair of
generators (elements of `k`) commutes. -/
@[to_additive /-- The additive subgroup `closure k` generated by `k` is commutative if and only if
every pair of generators (elements of `k`) commutes additively. -/]
theorem isMulCommutative_closure_iff {k : Set G} :
    IsMulCommutative (closure k) ↔ ∀ x ∈ k, ∀ y ∈ k, x * y = y * x := by
  refine ⟨fun h x hx y hy => ?_, isMulCommutative_closure⟩
  haveI := h
  exact setLike_mul_comm (subset_closure hx) (subset_closure hy)

end

end Subgroup
