/-
Copyright (c) 2026 Axiomatic_AI. All rights reserved.
Released under Apache 2.0 license as described in the file LICENSE.
Authors: Winston Yin, Frank Koppens
-/
import AxQM.Concrete.DeutschCompressedReachable
import Mathlib.Topology.Algebra.Star.Unitary
import AxQM.Basic.API.QuditGate

/-!
# The reachable `G`-circuit matrices are operators of a register `Evolution` submonoid
(N&C Exercise 4.44, Deutsch-gate universality — the matrix→`Evolution` op-identification)

The matrix development of Exercise 4.44 realises the universality of the Deutsch gate
`G = C²(iR_x(πα))` (with ancillas held `|1⟩`) at the level of raw matrices. This file exhibits the
reachable circuit matrices as the operators of a submonoid of closed-system `Evolution`s of
`qudit D`.

## Main declarations
* `deutschReachableEvolutions fullEnc dataEnc e α` — the **register-level reachable `G`-circuit
  submonoid**: the submonoid of `Evolution (qudit D)` generated by the `quditGate` promotions of
  the reachable ancilla-preserving gates `deutschAncillaReachableGates fullEnc dataEnc e α`.
-/

open Matrix

namespace AxQM

noncomputable section

open AxQM.Concrete

/-- **The register-level reachable `G`-circuit submonoid.** The submonoid of `Evolution (qudit D)`
generated by the `quditGate` promotions of the reachable ancilla-preserving gates
`deutschAncillaReachableGates fullEnc dataEnc e α`. -/
noncomputable def deutschReachableEvolutions {M m n D d : ℕ} (fullEnc : (Fin M → Fin 2) ≃ Fin D)
    (dataEnc : (Fin m → Fin 2) ≃ Fin d) (e : Fin M ≃ Fin m ⊕ Fin n) (α : ℝ) :
    Submonoid (Evolution (qudit D)) :=
  Submonoid.closure
    {E | ∃ (N : Matrix (Fin D) (Fin D) ℂ) (hN : N ∈ Matrix.unitaryGroup (Fin D) ℂ),
      N ∈ deutschAncillaReachableGates fullEnc dataEnc e α ∧ E = quditGate hN}

end

end AxQM
