/-
Copyright (c) 2026 Axiomatic_AI. All rights reserved.
Released under Apache 2.0 license as described in the file LICENSE.
Authors: Winston Yin, Frank Koppens
-/
import AxQM.Basic.Evolution
import AxQM.Basic.Observable
import AxQM.Basic.API.PureState
import AxQM.Basic.API.Purity
import Mathlib.Analysis.CStarAlgebra.Exponential

/-!
# AxQM.Basic.API — the Hamiltonian propagator

Connecting the **continuous-time** picture of dynamics
(N&C §2.2.2, the Schrödinger equation `iℏ d|ψ⟩/dt = H|ψ⟩` with a
Hermitian **Hamiltonian** `H`) to the **discrete-time** picture (a unitary
`Evolution`). Solving the Schrödinger equation for a
time-independent `H` gives (N&C eq. 2.90–2.91)
`|ψ(t₂)⟩ = U(t₁,t₂) |ψ(t₁)⟩`,  `U(t₁,t₂) ≡ exp(-i H (t₂ - t₁) / ℏ)`.
-/

open scoped InnerProductSpace
open ContinuousLinearMap

noncomputable section

namespace AxQM

variable {S : QSystem}

/-- **A linear isometry equivalence of `S.space`, packaged as a unitary evolution of `S`.** The
standard bridge from an explicitly constructed unitary (as a `LinearIsometryEquiv`) to the
`Evolution` primitive. -/
def Evolution.ofLinearIsometryEquiv (L : S.space ≃ₗᵢ[ℂ] S.space) : Evolution S :=
  letI : CompleteSpace S.space := FiniteDimensional.complete ℂ S.space
  ⟨↑(Unitary.linearIsometryEquiv.symm L), (Unitary.linearIsometryEquiv.symm L).2⟩

/-- The evolution `Evolution.ofLinearIsometryEquiv L` acts as `L` on vectors: its underlying
operator applied to `x` is `L x`. -/
@[simp]
theorem Evolution.ofLinearIsometryEquiv_op_apply (L : S.space ≃ₗᵢ[ℂ] S.space) (x : S.space) :
    (Evolution.ofLinearIsometryEquiv L).op x = L x := by
  simp [Evolution.ofLinearIsometryEquiv, Unitary.coe_symm_linearIsometryEquiv_apply]

/-- **A unitary `Evolution` packaged as a linear isometry equivalence** of `S.space` — the inverse
direction of `Evolution.ofLinearIsometryEquiv`. A unitary operator on a (finite-dimensional,
hence complete) Hilbert space is exactly a linear isometry equivalence, so this repackages `U.op`
losslessly. -/
def Evolution.toIsometryEquiv (U : Evolution S) : S.space ≃ₗᵢ[ℂ] S.space :=
  letI : CompleteSpace S.space := FiniteDimensional.complete ℂ S.space
  Unitary.linearIsometryEquiv ⟨U.op, U.unitary⟩

/-- The linear isometry equivalence `Evolution.toIsometryEquiv U` acts as the evolution's operator
`U.op` on vectors. -/
@[simp]
theorem Evolution.toIsometryEquiv_apply (U : Evolution S) (x : S.space) :
    U.toIsometryEquiv x = U.op x := by
  letI : CompleteSpace S.space := FiniteDimensional.complete ℂ S.space
  exact DFunLike.congr_fun (Unitary.coe_linearIsometryEquiv_apply ⟨U.op, U.unitary⟩) x

/-- **The Hamiltonian propagator** `U(t₁,t₂) ≡ exp(-i H (t₂ - t₁) / ℏ)` (Nielsen–Chuang eq. 2.91),
packaged as an `Evolution S`. Given the Hamiltonian `H` (an `Observable`, i.e. a Hermitian
operator), Planck's constant `ℏ`, and two times `t₁ t₂`, this is the operator that solves the
Schrödinger equation, `|ψ(t₂)⟩ = U(t₁,t₂)|ψ(t₁)⟩`.
-/
def Observable.propagator (H : Observable S) (ℏ t₁ t₂ : ℝ) : Evolution S where
  op := NormedSpace.exp (((-Complex.I) * ((t₂ - t₁ : ℝ) : ℂ) / (ℏ : ℂ)) • H.op)
  unitary := by
    -- Reshape the physical exponent `-i(t₂-t₁)/ℏ • H.op` as `i • (s • H.op)` with the real
    -- scalar `s = -(t₂-t₁)/ℏ`, i.e. `i` times the self-adjoint operator `s • H.op`.
    have ha : IsSelfAdjoint (((-(t₂ - t₁) / ℏ : ℝ) : ℂ) • H.op) :=
      ((Complex.im_eq_zero_iff_isSelfAdjoint _).mp rfl).smul H.selfAdjoint
    have hc : ((-Complex.I) * ((t₂ - t₁ : ℝ) : ℂ) / (ℏ : ℂ)) • H.op
        = Complex.I • (((-(t₂ - t₁) / ℏ : ℝ) : ℂ) • H.op) := by
      rw [smul_smul]; push_cast; ring_nf
    rw [hc, ← selfAdjoint.expUnitary_coe ⟨((-(t₂ - t₁) / ℏ : ℝ) : ℂ) • H.op,
      selfAdjoint.mem_iff.mpr ha⟩]
    exact (selfAdjoint.expUnitary _).2

/-- **Nielsen–Chuang Exercise 2.55.** The time-evolution operator `U(t₁,t₂) = exp(-i H (t₂ - t₁) /
ℏ)` (eq. 2.91) generated by a Hamiltonian `H` is unitary. -/
theorem Observable.propagator_op_mem_unitary (H : Observable S) (ℏ t₁ t₂ : ℝ) :
    NormedSpace.exp (((-Complex.I) * ((t₂ - t₁ : ℝ) : ℂ) / (ℏ : ℂ)) • H.op)
      ∈ unitary (S →L[ℂ] S) := sorry

/-- **The adjoint evolution** `U†`, whose operator is the Hilbert-space adjoint of `U.op`. It is the
"uncompute" step of a compute–phase–uncompute circuit. -/
def Evolution.adjoint (U : Evolution S) : Evolution S where
  op := ContinuousLinearMap.adjoint U.op
  unitary := by
    -- `U.adjoint.op = star U.op`, so unitarity is the star-closure of the unitary group.
    rw [← ContinuousLinearMap.star_eq_adjoint]
    exact Unitary.star_mem U.unitary

@[simp]
theorem Evolution.adjoint_op (U : Evolution S) :
    U.adjoint.op = ContinuousLinearMap.adjoint U.op := rfl

/-- The co-isometry identity `U U† = 1` extracted from unitarity. -/
theorem Evolution.comp_adjoint_self (U : Evolution S) :
    U.op.comp (ContinuousLinearMap.adjoint U.op) = 1 := by
  have h := (Unitary.mem_iff.mp U.unitary).2
  rwa [ContinuousLinearMap.star_eq_adjoint, ContinuousLinearMap.mul_def] at h

/-- **`ψ` is an eigenstate of the evolution `U` with eigenvalue `μ`.** The pure-state
eigenvalue equation `U ψ = μ ψ`, with `μ : ℂ` a complex number (a unitary's eigenvalues lie on
the unit circle, so `μ` is generally complex, unlike an observable's real eigenvalues). -/
def Evolution.HasEigenstate (U : Evolution S) (μ : ℂ) (ψ : PureState S) : Prop :=
  U.op ψ.vec = μ • ψ.vec

/-- **`Evolution.op` distributes over a scalar-multiplied finite sum:** `V.op (c • Σᵢ g i) = c • Σᵢ
V.op (g i)`. -/
theorem Evolution.op_smul_sum (V : Evolution S) {ι : Type*} [Fintype ι] (c : ℂ)
    (g : ι → S.space) : V.op (c • ∑ i, g i) = c • ∑ i, V.op (g i) := by
  rw [map_smul, map_sum]

/-- **The two pictures of unitary dynamics agree on a pure state** (Nielsen & Chuang, Exercise 8.1).
The density operator of the unitarily-evolved pure state equals the pure state's density
operator evolved by conjugation: `(U.evolvePure ψ).toState = U.evolve ψ.toState`, i.e. `|Uψ⟩⟨Uψ|
= U|ψ⟩⟨ψ|U†`. This is the equivalence between the vector picture `|ψ⟩ → U|ψ⟩` and the density
picture `ρ → E(ρ) ≡ UρU†` for `ρ = |ψ⟩⟨ψ|`. -/
theorem toState_evolvePure (U : Evolution S) (ψ : PureState S) :
    (U.evolvePure ψ).toState = U.evolve ψ.toState := sorry

end AxQM
