/-
Copyright (c) 2026 Axiomatic_AI. All rights reserved.
Released under Apache 2.0 license as described in the file LICENSE.
Authors: Winston Yin, Frank Koppens
-/
import AxQM.Basic.API.PhaseFlipCode
import AxQM.Basic.API.ShorPhaseSyndrome

/-!
# AxQM.Basic.API — the stabilizer generators of the three-qubit phase-flip code

Infrastructure for Nielsen & Chuang **Exercise 10.46**: the stabilizer of the
three-qubit *phase-flip* code (logical codewords `|0_L⟩ = |+++⟩`, `|1_L⟩ = |−−−⟩`) is generated by
`X₁X₂` and `X₂X₃`. This file builds those two generators as **observables** on the three-qubit
register, together with their product `X₁X₃` (the third nontrivial stabilizer element), and shows
they are involutions that stabilize the code.

## Contents

* `xxIObservable = X ⊗ X ⊗ I` (`X₁X₂`), `ixxObservable = I ⊗ X ⊗ X` (`X₂X₃`), and their product
  `xixObservable = X ⊗ I ⊗ X` (`X₁X₃`) as observables on `bitFlipReg`.
* `pmQubitState` / `phaseFlipCodewordState` — the `±` frame and the logical codewords `|+++⟩`,
  `|−−−⟩` as `PureState`s (so the exercise's stabilization claim is a statement over the
  primitives).
-/

open scoped InnerProductSpace TensorProduct
open ContinuousLinearMap

noncomputable section

namespace AxQM

/-- **`X₁X₂ = X ⊗ X ⊗ I`**, the first phase-flip stabilizer generator: the `X`-analogue of the
bit-flip syndrome observable `zzIObservable = Z₁Z₂`. -/
def xxIObservable : Observable bitFlipReg :=
  pauliXObservable.tmul (pauliXObservable.tmul (Observable.id qubit))

/-- **`X₂X₃ = I ⊗ X ⊗ X`**, the second phase-flip stabilizer generator (the `X`-analogue of
`izzObservable = Z₂Z₃`). -/
def ixxObservable : Observable bitFlipReg :=
  (Observable.id qubit).tmul (pauliXObservable.tmul pauliXObservable)

/-- **`X₁X₃ = X ⊗ I ⊗ X`**, the product `X₁X₂ · X₂X₃` of the two generators — the third nontrivial
element of the stabilizer group `⟨X₁X₂, X₂X₃⟩ = {I, X₁X₂, X₂X₃, X₁X₃}`. -/
def xixObservable : Observable bitFlipReg :=
  pauliXObservable.tmul ((Observable.id qubit).tmul pauliXObservable)

/-- **The single-qubit `±` frame as pure states** `{|+⟩, |−⟩}` (`0 ↦ |+⟩`, `1 ↦ |−⟩`); the
`PureState` companion of the vector frame `pmQubit`. -/
def pmQubitState : Fin 2 → PureState qubit := ![qubitPlus, qubitMinus]

/-- **The logical codewords of the three-qubit phase-flip code as pure states:**
`|0_L⟩ = |+++⟩` (`a = 0`) and `|1_L⟩ = |−−−⟩` (`a = 1`), so the exercise's "the generators stabilize
the code" is a genuine statement over the primitives (`Observable.HasEigenstate` on a
`PureState`). -/
def phaseFlipCodewordState (a : Fin 2) : PureState bitFlipReg :=
  (pmQubitState a).tmul ((pmQubitState a).tmul (pmQubitState a))

end AxQM
