/-
Copyright (c) 2026 Axiomatic_AI. All rights reserved.
Released under Apache 2.0 license as described in the file LICENSE.
Authors: Winston Yin, Frank Koppens
-/
import AxQM.Basic.API.PhaseFlipStabilizer

/-!
# Nielsen & Chuang, Exercise 10.46 — the phase-flip code stabilizer is generated by X₁X₂ and X₂X₃

*(N&C p. 467.)*

Stabilizer for three qubit phase flip code is generated by X1X2 and X2X3.

* `xxIObservable_hasEigenstate_one_phaseFlipCodewordState` — `X₁X₂ |σσσ⟩ = |σσσ⟩` for `σ ∈ {+, −}`.
* `ixxObservable_hasEigenstate_one_phaseFlipCodewordState` — `X₂X₃ |σσσ⟩ = |σσσ⟩`.
* `xixObservable_hasEigenstate_one_phaseFlipCodewordState` — `X₁X₃ |σσσ⟩ = |σσσ⟩` (the product
  element, so the whole group `⟨X₁X₂, X₂X₃⟩` stabilizes the code).
-/

open AxQM

namespace AxQM

/-- **Nielsen & Chuang, Exercise 10.46 (containment, generator `X₁X₂`).** The first phase-flip
stabilizer generator `X₁X₂ = X ⊗ X ⊗ I` fixes both logical codewords `|+++⟩`, `|−−−⟩`: each is a
`+1`-eigenstate. On `|σσσ⟩` the operator `X₁X₂` reads the sign `(−1)^{σ+σ} = +1`, so it stabilizes
the code. -/
theorem xxIObservable_hasEigenstate_one_phaseFlipCodewordState (a : Fin 2) :
    xxIObservable.HasEigenstate 1 (phaseFlipCodewordState a) := sorry

/-- **Nielsen & Chuang, Exercise 10.46 (containment, generator `X₂X₃`).** The second phase-flip
stabilizer generator `X₂X₃ = I ⊗ X ⊗ X` fixes both logical codewords `|+++⟩`, `|−−−⟩`: each is a
`+1`-eigenstate. -/
theorem ixxObservable_hasEigenstate_one_phaseFlipCodewordState (a : Fin 2) :
    ixxObservable.HasEigenstate 1 (phaseFlipCodewordState a) := sorry

/-- **Nielsen & Chuang, Exercise 10.46 (containment, product element `X₁X₃`).** The third
nontrivial stabilizer element `X₁X₃ = X ⊗ I ⊗ X`, the product `X₁X₂ · X₂X₃`, also fixes both
logical codewords `|+++⟩`, `|−−−⟩`: each is a `+1`-eigenstate. Together with the two generator
cases, this shows *every* element of the group `⟨X₁X₂, X₂X₃⟩ = {I, X₁X₂, X₂X₃, X₁X₃}` stabilizes
the phase-flip code (`⟨X₁X₂, X₂X₃⟩ ⊆ S`). -/
theorem xixObservable_hasEigenstate_one_phaseFlipCodewordState (a : Fin 2) :
    xixObservable.HasEigenstate 1 (phaseFlipCodewordState a) := sorry

end AxQM
