/-
Copyright (c) 2026 Axiomatic_AI. All rights reserved.
Released under Apache 2.0 license as described in the file LICENSE.
Authors: Winston Yin, Frank Koppens
-/
module

public import Mathlib.LinearAlgebra.Matrix.ToLin

/-!
# Generator matrices: adding one column to another preserves the code

Following Nielsen & Chuang, *Quantum Computation and Quantum Information*, §10.4.1, a **generator
matrix** `G` (an `m × n` matrix over a ring) encodes a message column vector `x` as `G *ᵥ x`, and
the **code** it generates is the set of all codewords `{G *ᵥ x}` — equivalently, the span of the
columns of `G`, i.e. the range of the encoding map `x ↦ G *ᵥ x` (`Matrix.mulVecLin`).

## Main definitions

* `Matrix.addCol M i j`: the elementary column operation that **adds column `i` to column `j`**,
  replacing column `j` of `M` with `col j + col i` and leaving every other column unchanged.

## Main results

* `Matrix.range_mulVecLin_addCol`: for distinct columns `i ≠ j`, the code generated by
  `M.addCol i j` equals the code generated by `M`
  (`(M.addCol i j).mulVecLin.range = M.mulVecLin.range`) — Exercise 10.15.
-/

@[expose] public section

namespace Matrix

variable {α : Type*} {m n : Type*}

/-- **Add column `i` to column `j`** of the matrix `M` (Nielsen & Chuang, Exercise 10.15):
column `j` of `M` is replaced by `col j + col i`, and every other column is unchanged. -/
def addCol [Add α] [DecidableEq n] (M : Matrix m n α) (i j : n) : Matrix m n α :=
  M.updateCol j (fun a => M a j + M a i)

/-- **Adding one column of a generator matrix to another generates the same code** (Nielsen &
Chuang, Exercise 10.15, p. 446). -/
theorem range_mulVecLin_addCol {R : Type*} [CommRing R] {m n : Type*} [Fintype n] [DecidableEq n]
    (M : Matrix m n R) {i j : n} (hij : i ≠ j) :
    LinearMap.range (M.addCol i j).mulVecLin = LinearMap.range M.mulVecLin := sorry

end Matrix
