/-
Copyright (c) 2026 Axiomatic_AI. All rights reserved.
Released under Apache 2.0 license as described in the file LICENSE.
Authors: Winston Yin, Frank Koppens
-/
module

public import AxQM.ToMathlib.InformationTheory.Coding.DualCode
public import AxQM.ToMathlib.InformationTheory.Coding.GeneratorMatrix

/-!
# Weak self-duality of a code from its generator matrix

A **generator matrix** `G` encodes a message column vector `x` as the codeword `G *ᵥ x`, so the code
it generates is the range of the encoding map `x ↦ G *ᵥ x` (`Matrix.mulVecLin`), i.e. the span of
the columns of `G` (Nielsen & Chuang, *Quantum Computation and Quantum Information*, §10.4.1). The
code is **weakly self-dual** (self-orthogonal, `LinearCode.IsSelfOrthogonal`) when every two
codewords are orthogonal under the standard dot product, `C ⊆ C⊥`.

## Main results

* `LinearCode.isSelfOrthogonal_range_mulVecLin_iff`: the code `range G.mulVecLin` generated by a
  matrix `G` is weakly self-dual iff the Gram matrix `Gᵀ * G` vanishes.
-/

open Matrix

@[expose] public section

namespace LinearCode

variable {K m n : Type*} [Field K] [Fintype m] [Fintype n] [DecidableEq m]

/-- **Nielsen & Chuang, Exercise 10.24** (p. 450): the code generated by a matrix `G` — the range of
the encoding map `x ↦ G *ᵥ x` (`Matrix.mulVecLin`), i.e. the column span of `G` — is **weakly
self-dual** (self-orthogonal, `C ⊆ C⊥`) if and only if the Gram matrix `Gᵀ * G` vanishes. -/
theorem isSelfOrthogonal_range_mulVecLin_iff (G : Matrix m n K) :
    IsSelfOrthogonal (LinearMap.range G.mulVecLin) ↔ Gᵀ * G = 0 := sorry

end LinearCode

end
