/-
Copyright (c) 2026 Axiomatic_AI. All rights reserved.
Released under Apache 2.0 license as described in the file LICENSE.
Authors: Winston Yin, Frank Koppens
-/
module

public import Mathlib.Data.Matrix.ColumnRowPartitioned
public import Mathlib.LinearAlgebra.Matrix.ToLin

/-!
# The generator matrix of a parity check in standard form

Following Nielsen & Chuang, *Quantum Computation and Quantum Information*, §10.4.1, a linear code
can be presented either as the **kernel** of a parity-check matrix `H` (`H x = 0`, eq. (10.57)), or
as the **column span** of a generator matrix `G` (the range of the encoding map `x ↦ G *ᵥ x`); the
two presentations describe the same code. A parity-check matrix can always be brought to the
**standard form** `H = [A ∣ I_{n-k}]`.

## Main definitions

* `Matrix.stdParityCheck A`: the **standard-form parity-check matrix** `H = [A ∣ I]`, a
  `Matrix μ (κ ⊕ μ) R` (`Matrix.fromCols A 1`).
* `Matrix.stdGenerator A`: the **corresponding generator matrix** `G = [I; -A]`, a
  `Matrix (κ ⊕ μ) κ R` (`Matrix.fromRows 1 (-A)`).

## Main results

* `Matrix.stdGenerator_mulVecLin_injective`: the columns of `G` are linearly independent (`G` has
  full column rank `k`), so `G` is a genuine `[n, k]` generator matrix.
* `Matrix.range_mulVecLin_stdGenerator`: **Exercise 10.19 itself** — the code generated by `G` (the
  range of `x ↦ G *ᵥ x`) equals the code with parity check `H` (the kernel of `z ↦ H *ᵥ z`):
  `range (stdGenerator A).mulVecLin = ker (stdParityCheck A).mulVecLin`.
-/

@[expose] public section

namespace Matrix

variable {R : Type*} [CommRing R] {κ μ : Type*}
  [Fintype κ] [Fintype μ] [DecidableEq κ] [DecidableEq μ]

/-- The **standard-form parity-check matrix** `H = [A ∣ I_{n-k}]` (Nielsen & Chuang, §10.4.1,
Exercise 10.19): the `(n-k) × n` matrix over `R` whose first `k` columns are `A : Matrix μ κ R` and
whose last `n - k` columns are the identity, with the `n = k + (n-k)` coordinates indexed by
`κ ⊕ μ`. The code it defines is its kernel `{z ∣ H z = 0}`. -/
def stdParityCheck (A : Matrix μ κ R) : Matrix μ (κ ⊕ μ) R := A.fromCols 1

/-- The **generator matrix corresponding** to the standard-form parity check `[A ∣ I]` (Nielsen &
Chuang, Exercise 10.19, eq. (10.59)): the `n × k` matrix `G = [I_k; -A]` whose top `k` rows are the
identity and whose bottom `n - k` rows are `-A`. Encoding a message `x` as `G *ᵥ x` copies `x` into
the message positions and fills the check positions with `-A *ᵥ x`. -/
def stdGenerator (A : Matrix μ κ R) : Matrix (κ ⊕ μ) κ R := (1 : Matrix κ κ R).fromRows (-A)

omit [Fintype μ] [DecidableEq μ] in
/-- **The columns of the generator `G = [I; -A]` are linearly independent** (Nielsen & Chuang, p.
446). Hence `G` has full column rank `k` and is a genuine `[n, k]` generator matrix. -/
theorem stdGenerator_mulVecLin_injective (A : Matrix μ κ R) :
    Function.Injective (stdGenerator A).mulVecLin := sorry

/-- **Nielsen & Chuang, Exercise 10.19** (p. 447, eq. (10.59)): for a parity-check matrix in the
standard form `H = [A ∣ I_{n-k}]`, the matrix `G = [I_k; -A]` is a corresponding generator
matrix. -/
theorem range_mulVecLin_stdGenerator (A : Matrix μ κ R) :
    LinearMap.range (stdGenerator A).mulVecLin = LinearMap.ker (stdParityCheck A).mulVecLin := sorry

end Matrix

end
