/-
Copyright (c) 2026 Axiomatic_AI. All rights reserved.
Released under Apache 2.0 license as described in the file LICENSE.
Authors: Winston Yin, Frank Koppens
-/
import AxQM.Concrete.CSSStabilizerGenerators
import AxQM.Concrete.PauliGroup
import Mathlib.GroupTheory.Subgroup.Centralizer

/-!
# Concrete: the CSS stabilizer subgroup `cssStabilizer C₁ C₂`

**Nielsen & Chuang, Exercise 10.51** — *the check matrix (10.106) is the stabilizer of the CSS code
`CSS(C₁, C₂)`* (p. 470). The `X`-type / `Z`-type generator strings are assembled into a **subgroup
of the `n`-qubit Pauli group**, which is **abelian**.

## Contents

* `cssStabilizer` — the subgroup (of the finite Pauli group `PauliGroup n`).
-/

open Matrix

namespace AxQM.Concrete

variable {n : ℕ}

/-- The **`X`-type Pauli-group generator** `X^v` of a binary support vector `v : Fin n → ZMod 2`:
the phase-`0` element `(0, xString v)` of the Pauli group whose matrix is the `X`-type Pauli string
`pauliString (xString v)`. These are the generators from the top block `H(C₂⊥)` of the CSS check
matrix (10.106). -/
def xPauli (v : Fin n → ZMod 2) : PauliGroup n := ⟨0, xString v⟩

/-- The **`Z`-type Pauli-group generator** `Z^u` of a binary support vector `u : Fin n → ZMod 2`:
the phase-`0` element `(0, zString u)` of the Pauli group whose matrix is the `Z`-type Pauli string
`pauliString (zString u)`. These are the generators from the bottom block `H(C₁)` of the CSS check
matrix (10.106). -/
def zPauli (u : Fin n → ZMod 2) : PauliGroup n := ⟨0, zString u⟩

/-- **The CSS stabilizer group of the check matrix (10.106)**:
the subgroup of the `n`-qubit Pauli group `PauliGroup n` generated by the `X`-type strings `X^v`
(`v ∈ C₂`, the row space of `H(C₂⊥)`) and the `Z`-type strings `Z^u` (`u ∈ C₁⊥`, the row space of
`H(C₁)`). The generating set is basis-free — indexed by *all* codewords of `C₂` and `C₁⊥`, not a
chosen basis — so the group depends only on the codes `C₁, C₂`, not on a choice of parity-check
matrix. -/
def cssStabilizer (C₁ C₂ : LinearCode (ZMod 2) (Fin n)) : Subgroup (PauliGroup n) :=
  Subgroup.closure ((xPauli '' (C₂ : Set (Fin n → ZMod 2))) ∪
    (zPauli '' (C₁.dual : Set (Fin n → ZMod 2))))

end AxQM.Concrete
