/-
Copyright (c) 2026 Axiomatic_AI. All rights reserved.
Released under Apache 2.0 license as described in the file LICENSE.
Authors: Winston Yin, Frank Koppens
-/
import AxQM.Concrete.DeutschGateDensity
import AxQM.Concrete.AxisAngleGateValues
import AxQM.Concrete.Pauli
import AxQM.Concrete.SqrtSwapCNOT
import Mathlib.Topology.Instances.Matrix

/-!
# Concrete: the Deutsch target orbit (matrix level, N&C Ex 4.44)

The powers of the Deutsch target `iR_x(πα)`, the target operations of the once-controlled gates
`C(g) = |0⟩⟨0| ⊗ 1 + |1⟩⟨1| ⊗ g` of Nielsen & Chuang, Exercise 4.44.
-/

namespace AxQM.Concrete

open Matrix
open scoped Kronecker

variable {τ : Type*} [Fintype τ] [DecidableEq τ]

/-- **The Deutsch target orbit** `⟨iR_x(πα)⟩ = {iⁿ · R_x(nπα) : n ∈ ℤ}` — the cyclic subgroup
generated by the Deutsch target `iR_x(πα)`, as a set of raw `2 × 2` matrices. -/
noncomputable def deutschTargetOrbit (α : ℝ) : Set (Matrix (Fin 2) (Fin 2) ℂ) :=
  Set.range fun n : ℤ => Complex.I ^ n • rotX (n • (Real.pi * α))

end AxQM.Concrete
