/-
Copyright (c) 2026 Axiomatic_AI. All rights reserved.
Released under Apache 2.0 license as described in the file LICENSE.
Authors: Winston Yin, Frank Koppens
-/
import AxQM.Concrete.StabilizerCodeDimension
import AxQM.Concrete.StabilizerErrorCorrection
import AxQM.Concrete.PauliSubgroupNormalizer
import AxQM.Concrete.PauliStringCommutation
import AxQM.Concrete.PauliGroupNegOne

/-!
# Concrete: the five-qubit code stabilizer (Nielsen & Chuang §10.5.6, Fig 10.12)

The stabilizer group of the **five-qubit code** `[[5,1,3]]` (Exercise 10.49).
-/

open Matrix

namespace AxQM.Concrete

/-- The four **five-qubit code generators** as Pauli-string index vectors `Fin 5 → Fin 4`
(`I = 0, X = 1, Y = 2, Z = 3`), Figure 10.12: `g₁ = XZZXI`, `g₂ = IXZZX`, `g₃ = XIXZZ`,
`g₄ = ZXIXZ`. Each is the cyclic right-shift of the one before it. -/
def fiveQubitGenIdx : Fin 4 → (Fin 5 → Fin 4) :=
  ![![1, 3, 3, 1, 0], ![0, 1, 3, 3, 1], ![1, 0, 1, 3, 3], ![3, 1, 0, 1, 3]]

/-- The four five-qubit code generators as elements of the Pauli group `G₅` (overall phase `+1`),
i.e. the honest Hermitian Pauli operators `g₁ = XZZXI`, …, `g₄ = ZXIXZ` of Figure 10.12. -/
def fiveQubitGen (i : Fin 4) : PauliGroup 5 := ⟨0, fiveQubitGenIdx i⟩

/-- The **five-qubit code stabilizer** `S = ⟨g₁, g₂, g₃, g₄⟩`, the subgroup of `G₅` generated by the
four Figure-10.12 generators. -/
def fiveQubitStab : Subgroup (PauliGroup 5) := Subgroup.closure (Set.range fiveQubitGen)

/-- The **error set `{I} ∪ {single-qubit Paulis}`** for the five-qubit code, indexed by `Fin 16`:
`E₀ = I`, then the fifteen single-qubit errors `Xᵢ, Yᵢ, Zᵢ` (`i = 0,…,4`), each an honest
(phase `+1`) Pauli-group element. This is Nielsen & Chuang's error set of `I` together with every
single-qubit error. -/
def fiveQubitError : Fin 16 → PauliGroup 5 :=
  ![⟨0, ![0, 0, 0, 0, 0]⟩,
    ⟨0, ![1, 0, 0, 0, 0]⟩, ⟨0, ![2, 0, 0, 0, 0]⟩, ⟨0, ![3, 0, 0, 0, 0]⟩,
    ⟨0, ![0, 1, 0, 0, 0]⟩, ⟨0, ![0, 2, 0, 0, 0]⟩, ⟨0, ![0, 3, 0, 0, 0]⟩,
    ⟨0, ![0, 0, 1, 0, 0]⟩, ⟨0, ![0, 0, 2, 0, 0]⟩, ⟨0, ![0, 0, 3, 0, 0]⟩,
    ⟨0, ![0, 0, 0, 1, 0]⟩, ⟨0, ![0, 0, 0, 2, 0]⟩, ⟨0, ![0, 0, 0, 3, 0]⟩,
    ⟨0, ![0, 0, 0, 0, 1]⟩, ⟨0, ![0, 0, 0, 0, 2]⟩, ⟨0, ![0, 0, 0, 0, 3]⟩]

/-- The five-qubit stabilizer is finite, being a subgroup of the finite Pauli group `G₅`. -/
noncomputable instance : Fintype ↥fiveQubitStab := Fintype.ofFinite _

/-- **Nielsen & Chuang, Exercise 10.49.** The five-qubit code corrects any single-qubit error.
For the five-qubit stabilizer `S = ⟨g₁,…,g₄⟩` there is a trace-preserving
recovery operation `R` (`∑ₒ Rₒ† Rₒ = 1`) that **corrects** the error set
`{I} ∪ {single-qubit Paulis}` on the code space `C(S)`: the set is a *correctable set of
errors*. -/
theorem fiveQubitCode_isCorrectableErrorSet :
    ∃ (κ : Type) (_ : Fintype κ)
      (R : κ → EuclideanSpace ℂ (Fin 5 → Fin 2) →L[ℂ] EuclideanSpace ℂ (Fin 5 → Fin 2)),
      (∑ o, (ContinuousLinearMap.adjoint (R o)).comp (R o) = 1) ∧
      (Matrix.toEuclideanCLM (𝕜 := ℂ) (n := Fin 5 → Fin 2) (codeProjector fiveQubitStab)).Corrects
        (fun i => Matrix.toEuclideanCLM (𝕜 := ℂ) (n := Fin 5 → Fin 2) (fiveQubitError i).toMat) R :=
          sorry

/-- The five-qubit code **logical `Z̄ = Z⊗Z⊗Z⊗Z⊗Z`** (§10.5.6) as a Pauli-string index vector. -/
def fiveQubitLogicalZBarIdx : Fin 5 → Fin 4 := ![3, 3, 3, 3, 3]

/-- The **encoded-`|0⟩` generating set** `⟨g₁, g₂, g₃, g₄, Z̄⟩` of the five-qubit code: the four
Figure-10.12 stabilizer generators (blocks `0,…,3`) together with the logical `Z̄` (block `4`). Its
simultaneous `+1`-eigenspace is the encoded `|0⟩` — the `+1`-eigenstate of `Z̄`, as opposed to the
encoded `|1⟩`, its `−1`-eigenstate. -/
def fiveQubitZeroGenIdx : Fin 5 → (Fin 5 → Fin 4) :=
  ![fiveQubitGenIdx 0, fiveQubitGenIdx 1, fiveQubitGenIdx 2, fiveQubitGenIdx 3,
    fiveQubitLogicalZBarIdx]

end AxQM.Concrete
