/-
Copyright (c) 2026 Axiomatic_AI. All rights reserved.
Released under Apache 2.0 license as described in the file LICENSE.
Authors: Winston Yin, Frank Koppens
-/
import AxQM.ToMathlib.InformationTheory.Coding.ParityCheck
import Mathlib.LinearAlgebra.Dimension.Constructions
import Mathlib.Algebra.Field.ZMod

/-!
# Concrete: the generator matrix of the `[7, 4, 3]` Hamming code (Nielsen & Chuang, Exercise 10.28)

The `[7, 4, 3]` Hamming code `C` is the classical ingredient of the Steane code (Nielsen & Chuang,
*Quantum Computation and Quantum Information*, §10.4.4).

## Main results (Nielsen & Chuang, Exercise 10.28)

* `hammingGenerator_isGenerator`: **Exercise 10.28 itself** — the code generated by `G` (the range
  of `x ↦ G *ᵥ x`) equals the parity-check code (the kernel of `x ↦ H *ᵥ x`):
  `range hammingGenerator.mulVecLin = ofParityCheck hammingParityCheck`.
-/

namespace AxQM.Concrete

open Matrix

/-- The **parity-check matrix** of the `[7, 4, 3]` Hamming code `C` (Nielsen & Chuang, eq. (10.76)):
the `3 × 7` matrix over `ZMod 2` whose columns are the binary numerals `1, …, 7`. The code is the
set of words annihilated by it, `LinearCode.ofParityCheck hammingParityCheck`. -/
def hammingParityCheck : Matrix (Fin 3) (Fin 7) (ZMod 2) :=
  !![0, 0, 0, 1, 1, 1, 1;
     0, 1, 1, 0, 0, 1, 1;
     1, 0, 1, 0, 1, 0, 1]

/-- The **transposed generator matrix** `H[C₂] = G[C₁]ᵀ` displayed in Nielsen & Chuang eq. (10.77):
the `4 × 7` matrix over `ZMod 2` whose rows are the four generators of the `[7, 4, 3]` Hamming code
`C = C₁` (equivalently, the parity-check matrix of the dual `C₂ = C⊥`). Exercise 10.28 verifies that
its **transpose** `hammingGenerator` generates `C`. -/
def hammingCheckC2 : Matrix (Fin 4) (Fin 7) (ZMod 2) :=
  !![1, 0, 0, 0, 0, 1, 1;
     0, 1, 0, 0, 1, 0, 1;
     0, 0, 1, 0, 1, 1, 0;
     0, 0, 0, 1, 1, 1, 1]

/-- The **generator matrix** of the `[7, 4, 3]` Hamming code (Nielsen & Chuang, Exercise 10.28): the
transpose of the matrix (10.77), a `7 × 4` matrix over `ZMod 2`. Its top `4 × 4` block is the
identity (message positions) and its bottom `3 × 4` block carries the parity data; the encoding map
`x ↦ hammingGenerator *ᵥ x` sends a `4`-bit message to its `7`-bit codeword. -/
def hammingGenerator : Matrix (Fin 7) (Fin 4) (ZMod 2) := hammingCheckC2ᵀ

/-- **Nielsen & Chuang, Exercise 10.28** (p. 452): the transpose of the matrix (10.77),
`hammingGenerator`, is the **generator** of the `[7, 4, 3]` Hamming code. -/
theorem hammingGenerator_isGenerator :
    LinearMap.range hammingGenerator.mulVecLin = LinearCode.ofParityCheck hammingParityCheck :=
      sorry

end AxQM.Concrete
