/-
Copyright (c) 2026 Axiomatic_AI. All rights reserved.
Released under Apache 2.0 license as described in the file LICENSE.
Authors: Winston Yin, Frank Koppens
-/
import AxQM.Concrete.QubitBasisOperators
import Mathlib.Analysis.InnerProductSpace.TensorProduct
import AxQM.ToMathlib.Analysis.InnerProductSpace.AdjointAntilinear

/-!
# Concrete: the resonant Jaynes–Cummings (vacuum-Rabi) unitary on two qubits (N&C §7.5.2, Ex 8.24)

The time-evolution operator generated by the resonant Jaynes–Cummings interaction — Nielsen &
Chuang eq. (7.77) with detuning `δ = 0` — on the tensor product `H ⊗[ℂ] H` of two abstract qubits,
the **atom** (left factor) and the single-mode **field** (right factor), each a two-dimensional
complex inner product space with a chosen computational orthonormal basis
`b : OrthonormalBasis (Fin 2) ℂ H`.

## The closed form

`U` is written in the closed form `U = I + (cos(gt) - 1) Q - i sin(gt) S`, where

* `S = σ₋ ⊗ σ₊ + σ₊ ⊗ σ₋` (`jcCoupling`) is the **excitation-exchange coupling** `|01⟩⟨10| +
  |10⟩⟨01|` — the operator content of the Jaynes–Cummings interaction `a†σ₋ + aσ₊` restricted to the
  ≤1-excitation sector; and
* `Q = P₀ ⊗ P₁ + P₁ ⊗ P₀` (`jcExchangeProj`) is the orthogonal **projector** `|01⟩⟨01| + |10⟩⟨10|`
  onto the single-excitation subspace.

## Contents

* `jcCoupling b`, `jcExchangeProj b` — the coupling `S` and the exchange projector `Q`.
* `jaynesCummingsZeroDetuningUnitary b g t` — the unitary `U` (eq. 7.77 at `δ = 0`).
-/

open scoped TensorProduct InnerProductSpace

noncomputable section

namespace AxQM.Concrete

variable {H : Type*} [NormedAddCommGroup H] [InnerProductSpace ℂ H] [FiniteDimensional ℂ H]
  [CompleteSpace H] (b : OrthonormalBasis (Fin 2) ℂ H)

/-- The **excitation-exchange coupling** `S = σ₋ ⊗ σ₊ + σ₊ ⊗ σ₋ = |01⟩⟨10| + |10⟩⟨01|` of the
resonant Jaynes–Cummings interaction: it swaps `|10⟩` (excited atom, empty field) with `|01⟩`
(ground atom, one photon), the operator content of `a†σ₋ + aσ₊` on the ≤1-excitation sector. -/
noncomputable def jcCoupling : H ⊗[ℂ] H →ₗ[ℂ] H ⊗[ℂ] H :=
  TensorProduct.map (qubitUnit b 0 1) (qubitUnit b 1 0)
    + TensorProduct.map (qubitUnit b 1 0) (qubitUnit b 0 1)

/-- The orthogonal **projector** `Q = P₀ ⊗ P₁ + P₁ ⊗ P₀ = |01⟩⟨01| + |10⟩⟨10|` onto the
single-excitation subspace `span{|01⟩, |10⟩}` on which the Rabi rotation acts. -/
noncomputable def jcExchangeProj : H ⊗[ℂ] H →ₗ[ℂ] H ⊗[ℂ] H :=
  TensorProduct.map (qubitUnit b 0 0) (qubitUnit b 1 1)
    + TensorProduct.map (qubitUnit b 1 1) (qubitUnit b 0 0)

/-- The **resonant Jaynes–Cummings (vacuum-Rabi) unitary** `U = I + (cos(gt) - 1) Q - i sin(gt) S`
(Nielsen & Chuang eq. 7.77 with detuning `δ = 0`): identity on `span{|00⟩, |11⟩}`, and a Rabi
rotation of angle `gt` exchanging a quantum of energy on `span{|01⟩, |10⟩}`. -/
noncomputable def jaynesCummingsZeroDetuningUnitary (g t : ℝ) : H ⊗[ℂ] H →ₗ[ℂ] H ⊗[ℂ] H :=
  LinearMap.id
    + ((Real.cos (g * t) : ℂ) - 1) • jcExchangeProj b
    + (-Complex.I * (Real.sin (g * t) : ℂ)) • jcCoupling b

end AxQM.Concrete

end
