/-
Copyright (c) 2026 Axiomatic_AI. All rights reserved.
Released under Apache 2.0 license as described in the file LICENSE.
Authors: Winston Yin, Frank Koppens
-/
import AxQM.Concrete.PauliGroup
import Mathlib.Data.ZMod.Basic
import Mathlib.LinearAlgebra.LinearIndependent.Defs

/-!
# Concrete: the structure of a Pauli subgroup `S` with `-I ∉ S`

The elementary group theory of a subgroup `S` of the `n`-qubit Pauli group `Gₙ` satisfying
`-I ∉ S` (`negOne n ∉ S`).

## The `-I ∉ S` structure (N&C Exercises 10.30, 10.34, 10.35)

* `imOne`, `negImOne` — the phase-only elements `iI = (1, 0)` and `-iI = (3, 0)`.
* `imOne_notMem_of_negOne_notMem`, `negImOne_notMem_of_negOne_notMem` — **N&C Exercise 10.30**:
  `-I ∉ S ⟹ ±iI ∉ S`.
* `sq_eq_one_of_negOne_notMem` — **`g² = I` for all `g ∈ S`** (N&C Exercise 10.35), and
  `toMat_isHermitian_of_negOne_notMem`, the same statement as N&C's `g† = g` on matrices.
* `sq_eq_one_and_ne_negOne_of_negOne_notMem_closure` — **N&C Exercise 10.34**, forward implication.
* `exists_gens_sq_one_ne_negOne_with_negOne_mem`,
  `exists_commuting_gens_sq_one_ne_negOne_with_negOne_mem` — the reverse implication of
  Exercise 10.34 is **false**, and remains false for commuting generators.
* `negOne_notMem_closure_iff_forall_sq_eq_one_and_ne_negOne` — the intended correct statement of
  Exercise 10.34, for commuting generators with `𝔽₂`-independent check rows.
-/

open scoped BigOperators
open scoped IsMulCommutative

namespace AxQM.Concrete

variable {n : ℕ}

namespace PauliGroup

/-- **N&C Exercise 10.35**: for a subgroup `S` of the Pauli group with `-I ∉ S`, every `g ∈ S`
satisfies `g² = I`. -/
theorem sq_eq_one_of_negOne_notMem {S : Subgroup (PauliGroup n)} (hS : negOne n ∉ S)
    {p : PauliGroup n} (hp : p ∈ S) : p ^ 2 = 1 := sorry

/-- **N&C Exercise 10.35** (`g† = g`, the operator form): for a subgroup `S` of the `n`-qubit Pauli
group with `-I ∉ S`, the operator `toMat g` of every `g ∈ S` is **Hermitian**, `(toMat g)ᴴ =
toMat g`. This is N&C's `g† = g` at the level of the actual matrix (`†` = the conjugate
transpose). -/
theorem toMat_isHermitian_of_negOne_notMem {S : Subgroup (PauliGroup n)} (hS : negOne n ∉ S)
    {p : PauliGroup n} (hp : p ∈ S) : (p.toMat).IsHermitian := sorry

/-- The Pauli-group element **`iI`**, i.e. `(1, 0)` (`i¹ · I = iI`). With `-iI` (`negImOne`) these
are the two phase-only elements N&C Exercise 10.30 excludes from a subgroup `S` with `-I ∉ S`. -/
def imOne (n : ℕ) : PauliGroup n := ⟨1, 0⟩

/-- The Pauli-group element **`-iI`**, i.e. `(3, 0)` (`i³ · I = -iI`). -/
def negImOne (n : ℕ) : PauliGroup n := ⟨3, 0⟩

/-- **N&C Exercise 10.30** (the `iI` half): for a subgroup `S` of the `n`-qubit Pauli group with
`-I ∉ S`, the element `iI` is not in `S`. -/
theorem imOne_notMem_of_negOne_notMem {S : Subgroup (PauliGroup n)} (hS : negOne n ∉ S) :
    imOne n ∉ S := sorry

/-- **N&C Exercise 10.30** (the `-iI` half): for a subgroup `S` of the `n`-qubit Pauli group with
`-I ∉ S`, the element `-iI` is not in `S`. -/
theorem negImOne_notMem_of_negOne_notMem {S : Subgroup (PauliGroup n)} (hS : negOne n ∉ S) :
    negImOne n ∉ S := sorry

/-- **N&C Exercise 10.34, forward implication** (the true half). Let `S = ⟨g₁,…,g_l⟩ = closure T` be
the subgroup generated by a set `T` of Pauli-group elements. If `-I ∉ S` then every generator `g
∈ T` satisfies `g² = I` and `g ≠ -I`. (The converse is **false**.) -/
theorem sq_eq_one_and_ne_negOne_of_negOne_notMem_closure {T : Set (PauliGroup n)}
    (hS : negOne n ∉ Subgroup.closure T) {g : PauliGroup n} (hg : g ∈ T) :
    g ^ 2 = 1 ∧ g ≠ negOne n := sorry

/-- **N&C Exercise 10.34, reverse implication is false.** There is a set `T` of Pauli-group elements
each satisfying `g² = I` and `g ≠ -I`, whose generated subgroup `⟨T⟩` nevertheless contains
`-I`. This refutes the `⟸` direction of the exercise's `⟺`. -/
theorem exists_gens_sq_one_ne_negOne_with_negOne_mem :
    ∃ T : Set (PauliGroup 1),
      (∀ g ∈ T, g ^ 2 = 1 ∧ g ≠ negOne 1) ∧ negOne 1 ∈ Subgroup.closure T := sorry

/-- **N&C Exercise 10.34, reverse implication is false even for COMMUTING generators.** There is a
generating set of *commuting* Pauli-group elements, each squaring to `I` and different from
`-I`, whose generated subgroup contains `-I`. Hence the `⟸` direction of the exercise's `⟺` fails
**even under §10.5's standing abelian convention**. The genuinely omitted hypothesis is
`𝔽₂`-**independence** of the generators (N&C Proposition 10.3). -/
theorem exists_commuting_gens_sq_one_ne_negOne_with_negOne_mem :
    ∃ T : Set (PauliGroup 1),
      (∀ g ∈ T, g ^ 2 = 1 ∧ g ≠ negOne 1) ∧
        (∀ g ∈ T, ∀ h ∈ T, g * h = h * g) ∧
          negOne 1 ∈ Subgroup.closure T := sorry

/-- **N&C Exercise 10.34, the intended correct statement (the `⟺`).** The book's biconditional
`-I ∉ ⟨g₁, …, g_l⟩ ⟺ (gⱼ² = I ∧ gⱼ ≠ -I ∀j)` is false as literally stated; it becomes true once the
two hypotheses N&C's context supplies are restored — the generators **commute** and their check rows
are `𝔽₂`-**independent** (equivalently, by Proposition 10.3, the generators are independent). Under
these standing hypotheses the biconditional holds with exactly the exercise's right-hand side. -/
theorem negOne_notMem_closure_iff_forall_sq_eq_one_and_ne_negOne {l : ℕ}
    {g : Fin l → PauliGroup n} (hcomm : ∀ i j, g i * g j = g j * g i)
    (hindep : LinearIndependent (ZMod 2) fun i => (g i).checkRowHom) :
    negOne n ∉ Subgroup.closure (Set.range g) ↔ ∀ i, g i ^ 2 = 1 ∧ g i ≠ negOne n := sorry

end PauliGroup

end AxQM.Concrete
