/-
Copyright (c) 2026 Axiomatic_AI. All rights reserved.
Released under Apache 2.0 license as described in the file LICENSE.
Authors: Winston Yin, Frank Koppens
-/
import Mathlib.Analysis.SpecialFunctions.Gaussian.FourierTransform

/-!
# Concrete: exponential sensitivity to phase damping (N&C, Exercise 8.31)

Nielsen & Chuang, *Quantum Computation and Quantum Information*, **Exercise 8.31** (p. 386,
*Exponential sensitivity*), in terms of density-matrix elements over the harmonic oscillator's
number basis.

## Contents

* `phaseDampingDecayFactor` — the decay factor `e^{-λ k²}`.
* `phaseKickElem` — the phase-kicked density-matrix element `⟨n| D(θ) ρ D(θ)† |m⟩`.
* `phaseDampedElem` — the phase-damped element `⟨n| E(ρ) |m⟩`, the Gaussian average.
* `phaseDampedElem_eq` — **Exercise 8.31:** `⟨n| E(ρ) |m⟩ = e^{-λ(n-m)²} · ρ_nm`.
-/

namespace AxQM.Concrete

open MeasureTheory

noncomputable section

/-- The **phase-damping decay factor** `e^{-λ k²}` by which the coherence `ρ_nm` between two number
states of the harmonic oscillator differing by `k = n - m` quanta is multiplied under phase damping
(N&C Exercise 8.31). It is `1` on the diagonal (`k = 0`, populations preserved) and shrinks
super-exponentially in the energy gap `|k|`. -/
def phaseDampingDecayFactor (lam k : ℝ) : ℝ := Real.exp (-(lam * k ^ 2))

/-- The **phase-kicked density-matrix element** `⟨n| D(θ) ρ D(θ)† |m⟩`, where the density operator
`ρ : Matrix ℕ ℕ ℂ` is written in the number (`a†a`-eigen) basis of the harmonic oscillator and
`D(θ) = exp(-i θ N)` is the diagonal unitary generated by the number operator `N = a†a` (the
system factor of N&C's phase-damping Hamiltonian `H = χ a†a (b + b†)`, eq. 8.126), so `D(θ)|n⟩ =
e^{-i n θ}|n⟩`. -/
def phaseKickElem (θ : ℝ) (ρ : Matrix ℕ ℕ ℂ) (n m : ℕ) : ℂ :=
  Complex.exp (-Complex.I * (n : ℂ) * (θ : ℂ)) * ρ n m * Complex.exp (Complex.I * (m : ℂ) * (θ : ℂ))

/-- The **phase-damped density-matrix element** `⟨n| E(ρ) |m⟩`: the phase-kicked element averaged
over a random phase kick `θ` drawn from a Gaussian of mean `0` and variance `2λ` (probability
density `(4πλ)^{-1/2} e^{-θ²/(4λ)}`), following N&C's phase-damping model (eq. 8.124 generalized to
the oscillator's number basis). This is the `(n,m)` entry of the phase-damping quantum operation
`E(ρ) = (4πλ)^{-1/2} ∫ D(θ) ρ D(θ)† e^{-θ²/(4λ)} dθ`. -/
def phaseDampedElem (lam : ℝ) (ρ : Matrix ℕ ℕ ℂ) (n m : ℕ) : ℂ :=
  (Real.sqrt (4 * Real.pi * lam) : ℂ)⁻¹ *
    ∫ θ : ℝ, phaseKickElem θ ρ n m * Complex.exp (-((θ : ℂ)) ^ 2 / (4 * (lam : ℂ)))

/-- **Exercise 8.31 (exponential sensitivity to phase damping).** Under phase damping the
harmonic-oscillator density-matrix element `ρ_nm = ⟨n|ρ|m⟩` decays exactly by the Gaussian
factor `e^{-λ (n-m)²}`: `⟨n| E(ρ) |m⟩ = e^{-λ (n-m)²} · ρ_nm`. The coherence between number
states thus decays super-exponentially in their energy difference `|n - m|`, while the
populations (`n = m`) are untouched. -/
theorem phaseDampedElem_eq {lam : ℝ} (hlam : 0 < lam) (ρ : Matrix ℕ ℕ ℂ) (n m : ℕ) :
    phaseDampedElem lam ρ n m
      = (phaseDampingDecayFactor lam ((n : ℝ) - (m : ℝ)) : ℂ) * ρ n m := sorry

end

end AxQM.Concrete
